      SUBROUTINE ulypmma(ra, rb, gaa, gbb, gab, elyp,
     -                dlypra, dgaa, dlyprb, dgbb, dgab)
      IMPLICIT NONE
c	..Scalar Arguments..
	DOUBLE PRECISION	ra, rb, gaa, gbb, gab, elyp,
     -					dlypra, dgaa, dlyprb, 
     -					dgbb, dgab
c =====================================================================
c Purpose
c =======
C******************************************************
C******  LYP CODE WITH DERIVATIVES GENERATED BY *******
C******               MATHEMATICA               *******
C******************************************************   
C******            D B K APRIL 7 1998           *******
*******************************************************
C
C  Lee-Yang-Parr non-local correlation term
C  ** OPEN SHELL **
C
C  reference
C  C.Lee, W.Yang and R.G.Parr,  Phys.Rev. B37 (1988) 785
C  B.Miehlich, A.Savin, H.Stoll and H.Preuss, Chem.Phys.Lett.
C
c Arguments
c =========
C
C  ra       -  alpha density at current grid point
C  rb       -  beta density at current grid point
C  gaa      -  absolute value of alpha density derivative squared
C  gbb      -  absolute value of beta density derivative squared
C  gab      -  mixed alpha-beta density derivative square
C  on exit
C
C  elyp     -  exchange energy contribution at current grid point
C  dlypra   -  alpha potential
C  dgaa     -  alpha potential derivative
C  dlyprb   -  beta potential
C  dgbb     -  beta potential derivative
C  dgab	  -  mixed alpha-beta potential derivative
C
c
c =====================================================================
c	..
c     ..Parameters..

c	Formula constants as defined in ref above
	DOUBLE PRECISION	a, b, c, d
      PARAMETER		   (a=0.04918d0,b=0.132d0,c=0.2533d0,d=0.349d0)

c	Numerical constants (cn='constant')
	DOUBLE PRECISION	cn1, cn3, cn4, cn5,cn6, cn7, cn8, cn9, cn10,
     -					cn11, cn12, cn18, cn23, cn24, cn47,
     -
     -					cn1o3, cn2o3, cn4o3, cn5o3, cn8o3, cn10o3,
     -					cn11o3, cn14o3,
     -					
     -					cn1o9, cnpi43, cn36p4   
      
	PARAMETER		   (cn36p4=36.462398978764777d0,
     -					cn1o3=0.33333333333333333d0,
     -					cn8o3=2.66666666666666667d0,
     -					cn1=1.0d0,
     -					cn3=3.0d0,
     -					cn4=4.0d0,
     -					cn5=5.0d0,
     -					cn6=6.0d0,
     -					cn7=7.0d0,
     -					cn8=8.0d0,
     -					cn9=9.0d0,	
     -					cn11=11.0d0,
     -					cn12=12.0d0,
     -					cn18=18.0d0,
     -					cn23=23.0d0,
     -					cn24=24.0d0,
     -					cn47=47.0d0,
     -					cn1o9=0.111111111111111111d0,
     -					cn4o3=1.33333333333333333d0,
     -					cn11o3=3.6666666666666667d0,
     -					cn10o3=3.3333333333333333d0,
     -					cn2o3=0.66666666666666667d0,
     -					cn10=10.0d0,
     -					cn14o3=4.6666666666666667d0,
     -					cn5o3=1.66666666666666667d0,
     -					cnpi43=4.6011511144704900d0)
	
		
c     ..
c     ..Local Scalars..
	DOUBLE PRECISION	r, rab, w, t, rtm13,
     -					fp2, fp1, fp3, dt, dw, 
     -					ddgaara, ddgaarb, ddgbbra, ddgbbrb,
     -					ddgabra, ddgabrb

c     ..
c     ..Executable Statements..
c
c**********************************************************************
c
c	energy elyp
c
	rab = ra*rb
	r = ra+rb

	rtm13 = r**(-cn1o3)

	w = (r**(-cn11o3))*DEXP(-c*rtm13)/(cn1+(d*rtm13))

	t = c*rtm13 + (d*rtm13)/(cn1+(d*rtm13))

	dgaa = -(a*b*
     -    (-rb**2 + 
     -      cn1o9*rab*
     -       (cn1 - cn3*t - 
     -         (ra*
     -          (-cn11 + t))/r
     -         ))*w)

	dgbb = -(a*b*
     -    (-ra**2 + 
     -      cn1o9*rab*
     -       (cn1 - cn3*t - 
     -         (rb*
     -          (-cn11 + t))/r
     -         ))*w)	 

	dgab = - a*b*w*(cn1o9*rab*(cn47-cn7*t)-cn4o3*(r**2))

	fp1 =  -(cn4*a*rab)/(r*(1 + (d*rtm13)))
	
	fp2 =  -cn36p4*a*b*w*rab*(ra**cn8o3 + rb**cn8o3)

	fp3 =  dgaa*gaa + dgab*gab + dgbb*gbb

	elyp =  (fp1 + fp2 + fp3)/r
     
c	Now for the derivatives
c	very ugly mathematica output
	
      dt = (-(d*r**cn2o3) - 
     -    c*(d + r**cn1o3)**2)/
     -    (cn3*r**cn4o3*
     -    (d + r**cn1o3)**2)

c

	dw =  -(cn10*d*
     -      r**cn1o3 + cn11*r**cn2o3 - 
     -     c*(d + r**cn1o3))/
     -  (cn3*DEXP((c/r**cn1o3))*
     -    r**cn14o3*
     -    (d + r**cn1o3)**2)
	
	
c
	ddgaara = (a*b*rb*
     -    ((-cn12*ra**2 - cn24*ra*rb - 
     -         rb**2 + 
     -         ((cn4*ra**2 + cn8*ra*rb + 
     -             cn3*rb**2)*
     -            (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -          (d + 
     -            r**
     -             cn1o3
     -            ) + 
     -         cn4*ra**3*
     -          dt + 
     -         cn7*ra**2*rb*
     -          dt + 
     -         cn3*ra*rb**2*
     -          dt)/
     -       (DEXP(
     -          (c/
     -            r**
     -             cn1o3
     -            ))*
     -         r**
     -          cn10o3*
     -         (d + 
     -           r**
     -            cn1o3)
     -         ) + 
     -      r*
     -       (-cn12*ra**2 + cn8*ra*rb + 
     -         cn9*rb**2 + 
     -         (ra*(cn4*ra + cn3*rb)*
     -            (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -          (d + 
     -            r**
     -             cn1o3
     -            ))*
     -       dw))/(cn9*r**2)	

c

	ddgaarb = a*b*(-(-cn18*rb + 
     -        ra*
     -         (cn1 - 
     -           (cn3*
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -            (d + 
     -             r**
     -             cn1o3
     -             ) - 
     -           (ra*
     -             (-cn11 + 
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             )/
     -             (d + 
     -             r**
     -             cn1o3
     -             )))/r) + 
     -        ra*rb*
     -         ((ra*
     -             (-cn11 + 
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             )/
     -             (d + 
     -             r**
     -             cn1o3
     -             )))/r**2
     -            - cn3*
     -            dt - 
     -           (ra*
     -             dt)/
     -            r))/
     -     (cn9*
     -       DEXP(
     -        (c/
     -          r**
     -           cn1o3))*
     -       r**
     -        cn10o3*
     -       (d + 
     -         r**
     -          cn1o3))
     -     - (-rb**2 + 
     -       (ra*rb*
     -          (1 - 
     -            (cn3*
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -             (d + 
     -             r**
     -             cn1o3
     -             ) - 
     -            (ra*
     -             (-cn11 + 
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             )/
     -             (d + 
     -             r**
     -             cn1o3
     -             )))/r))/cn9
     -       )*
     -     dw)
	
c

	ddgbbra =  a*b*(-(-cn18*ra + 
     -        rb*
     -         (cn1 - 
     -           (cn3*
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -            (d + 
     -             r**
     -             cn1o3
     -             ) - 
     -           (rb*
     -             (-cn11 + 
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             )/
     -             (d + 
     -             r**
     -             cn1o3
     -             )))/r) + 
     -        ra*rb*
     -         ((rb*
     -             (-cn11 + 
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             )/
     -             (d + 
     -             r**
     -             cn1o3
     -             )))/r**2
     -            - cn3*
     -            dt - 
     -           (rb*
     -             dt)/
     -            r))/
     -     (cn9*
     -       DEXP(
     -        (c/
     -          r**
     -           cn1o3))*
     -       r**
     -        cn10o3*
     -       (d + 
     -         r**
     -          cn1o3))
     -     - (-ra**2 + 
     -       (ra*rb*
     -          (cn1 - 
     -            (cn3*
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -             (d + 
     -             r**
     -             cn1o3
     -             ) - 
     -            (rb*
     -             (-cn11 + 
     -             (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             )/
     -             (d + 
     -             r**
     -             cn1o3
     -             )))/r))/cn9
     -       )*
     -     dw)
	

c

	ddgbbrb = (a*b*ra*
     -    ((-ra**2 - cn24*ra*rb - 
     -         cn12*rb**2 + 
     -         ((cn3*ra**2 + cn8*ra*rb + 
     -             cn4*rb**2)*
     -            (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -          (d + 
     -            r**
     -             cn1o3
     -            ) + 
     -         cn3*ra**2*rb*
     -          dt + 
     -         cn7*ra*rb**2*
     -          dt + 
     -         cn4*rb**3*
     -          dt)/
     -       (DEXP(
     -          (c/
     -            r**
     -             cn1o3
     -            ))*
     -         r**
     -          cn10o3*
     -         (d + 
     -           r**
     -            cn1o3)
     -         ) + 
     -      r*
     -       (cn9*ra**2 + cn8*ra*rb - 
     -         cn12*rb**2 + 
     -         (rb*(cn3*ra + cn4*rb)*
     -            (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -          (d + 
     -            r**
     -             cn1o3
     -            ))*
     -       dw))/(cn9*r**2)


c

	ddgabra =         (a*b*((cn24*ra - cn23*rb + 
     -         (cn7*rb*
     -            (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -          (d + 
     -            r**
     -             cn1o3
     -            ) + 
     -         cn7*ra*rb*
     -          dt)/
     -       (DEXP(
     -          (c/
     -            r**
     -             cn1o3
     -            ))*
     -         r**
     -          cn10o3*
     -         (d + 
     -           r**
     -            cn1o3)
     -         ) + 
     -      (cn12*ra**2 - cn23*ra*rb + 
     -         cn12*rb**2 + 
     -         (cn7*ra*rb*
     -            (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -          (d + 
     -            r**
     -             cn1o3
     -            ))*
     -       dw))/cn9


c

	ddgabrb = (a*b*((-cn23*ra + cn24*rb + 
     -         (cn7*ra*
     -            (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -          (d + 
     -            r**
     -             cn1o3
     -            ) + 
     -         cn7*ra*rb*
     -          dt)/
     -       (DEXP(
     -          (c/
     -            r**
     -             cn1o3
     -            ))*
     -         r**
     -          cn10o3*
     -         (d + 
     -           r**
     -            cn1o3)
     -         ) + 
     -      (cn12*ra**2 - cn23*ra*rb + 
     -         cn12*rb**2 + 
     -         (cn7*ra*rb*
     -            (c + d + 
     -             (c*d)/
     -             r**
     -             cn1o3
     -             ))/
     -          (d + 
     -            r**
     -             cn1o3
     -            ))*
     -       dw))/cn9


c

	dlypra = (-cn4*a*d*ra*rb)/
     -   (cn3*r**
     -      cn5o3*
     -     (d + 
     -        r**
     -         cn1o3)**2
     -     ) + 
     -  (4*a*ra*rb)/
     -   (r**
     -      cn5o3*
     -     (d + 
     -       r**
     -        cn1o3)) - 
     -  (4*a*rb)/
     -   (r**
     -      cn2o3*
     -     (d + 
     -       r**
     -        cn1o3)) - 
     -  (cn4*cn6**cn2o3*a*b*
     -     cnpi43*rb*
     -     (cn11*
     -        ra**cn8o3
     -        + cn3*
     -        rb**cn8o3))
     -    /(cn5*
     -     DEXP(
     -      (c/
     -        r**
     -         cn1o3))*
     -     r**
     -      cn10o3*
     -     (d + 
     -       r**
     -        cn1o3)) + 
     -  gaa*ddgaara + 
     -  gab*ddgabra + 
     -  gbb*ddgbbra - 
     -  (cn12*cn6**cn2o3*a*
     -     b*cnpi43*
     -     ra**cn11o3*rb*
     -     dw)
     -    /cn5 - 
     -  (cn12*cn6**cn2o3*a*
     -     b*cnpi43*
     -     ra*rb**cn11o3*
     -     dw)
     -    /cn5


c


	dlyprb = (-cn4*a*d*ra*rb)/
     -   (cn3*r**
     -      cn5o3*
     -     (d + 
     -        r**
     -         cn1o3)**2
     -     ) + 
     -  (4*a*ra*rb)/
     -   (r**
     -      cn5o3*
     -     (d + 
     -       r**
     -        cn1o3)) - 
     -  (cn4*a*ra)/
     -   (r**
     -      cn2o3*
     -     (d + 
     -       r**
     -        cn1o3)) - 
     -  (cn4*cn6**cn2o3*a*b*
     -     cnpi43*ra*
     -     (cn3*
     -        ra**
     -         cn8o3 + 
     -       cn11*rb**cn8o3
     -       ))/
     -   (cn5*DEXP(
     -      (c/
     -        r**
     -         cn1o3))*
     -     r**
     -      cn10o3*
     -     (d + 
     -       r**
     -        cn1o3)) + 
     -  gaa*ddgaarb + 
     -  gab*ddgabrb + 
     -  gbb*ddgbbrb - 
     -  (cn12*cn6**cn2o3*a*
     -     b*cnpi43*
     -     ra**cn11o3*rb*
     -     dw)
     -    /cn5 - 
     -  (cn12*cn6**cn2o3*a*
     -     b*cnpi43*
     -     ra*rb**cn11o3*
     -     dw)
     -    /cn5


	dgaa = dgaa+dgaa
	dgbb = dgbb+dgbb


C
      RETURN
      END